### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by samo313** [SforAiDl/KD_Lib#104] opened 2021-03-20 08:16 UTC
Hello 
some error occurs when I run the basic version of code
from KD_Lib import DML
from KD_Lib import ResNet18, ResNet50 
from KD_Lib import VanillaKD

ImportError: cannot import name 'VanillaKD' from 'KD_Lib' (/usr/local/lib/python3.7/dist-packages/KD_Lib/__init__.py)
how can I handle this error?

thanks

**Comment by Het-Shah** [comment] 2021-03-20 09:24
Can you tell us how you installed the library?

**Comment by samo313** [comment] 2021-03-20 11:07
> Can you tell us how you installed the library?

I use google colab and run the following code
!git clone https://github.com/SforAiDl/KD_Lib.git
!pip install KD-Lib
!pip install -r requirements.txt

**Comment by khizirsiddiqui** [comment] 2021-03-20 12:24
> > Can you tell us how you installed the library?
> 
> I use google colab and run the following commands
> !git clone https://github.com/SforAiDl/KD_Lib.git
> !pip install KD-Lib
> !pip install -r requirements.txt

Hey, seems like you didn't install the way mentioned it in README.rst or got confused between the two suggested. Try this way:

```bash
$ git clone https://github.com/SforAiDl/KD_Lib.git
$ cd KD_Lib
$ python setup.py install
```
You can run command line programs on colab by prefexing them with "!". Also, don't forget to restart runtime after you've installed it once and you may also need to "%cd KD_Lib" instead of "!" in a colab notebook.

Let us know if you encounter more issues.

**Comment by samo313** [comment] 2021-03-20 12:40
> > > Can you tell us how you installed the library?
> > 
> > 
> > I use google colab and run the following commands
> > !git clone https://github.com/SforAiDl/KD_Lib.git
> > !pip install KD-Lib
> > !pip install -r requirements.txt
> 
> Hey, seems like you didn't install the way mentioned it in README.rst or got confused between the two suggested. Try this way:
> 
> ```shell
> $ git clone https://github.com/SforAiDl/KD_Lib.git
> $ cd KD_Lib
> $ python setup.py install
> ```
> 
> You can run command line programs on colab by prefexing them with "!". Also, don't forget to restart runtime after you've installed it once and you may also need to "%cd KD_Lib" instead of "!" in a colab notebook.
> 
> Let us know if you encounter more issues.

your mentioned commands run successfully
`Finished processing dependencies for KD-Lib==0.0.3`

but I got the below error:
`
ImportError                               Traceback (most recent call last)
<ipython-input-2-3787597a9976> in <module>()
      3 from torchvision.datasets import MNIST
      4 from torchvision import datasets, transforms
----> 5 from KD_Lib import VanillaKD
      6 
      7 # This part is where you define your datasets, dataloaders, models and optimizers

ImportError: cannot import name 'VanillaKD' from 'KD_Lib' (/content/KD_Lib/KD_Lib/__init__.py)
`

**Comment by khizirsiddiqui** [comment] 2021-03-20 12:42
Can you try `from KD_Lib.KD import VanillaKD`? Seems like an issue, readme.rst wasn't updated after code restructuring. Thanks for pointing this out!

**Comment by samo313** [comment] 2021-03-20 12:46
> Can you try `from KD_Lib.KD import VanillaKD`? Seems like an issue, readme.rst wasn't updated after code restructuring. Thanks for pointing this out!

I tried it too but there is a problem

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-2fd3673388e9> in <module>()
      3 from torchvision.datasets import MNIST
      4 from torchvision import datasets, transforms
----> 5 from KD_Lib.KD import VanillaKD
      6 
      7 # This part is where you define your datasets, dataloaders, models and optimizers

3 frames
/content/KD_Lib/KD_Lib/KD/__init__.py in <module>()
     18 )
     19 
---> 20 from .text import BERT2LSTM, get_essentials

/content/KD_Lib/KD_Lib/KD/text/__init__.py in <module>()
----> 1 from .BERT2LSTM import BERT2LSTM, get_essentials

/content/KD_Lib/KD_Lib/KD/text/BERT2LSTM/__init__.py in <module>()
----> 1 from .bert2lstm import BERT2LSTM
      2 from .utils import get_essentials

/content/KD_Lib/KD_Lib/KD/text/BERT2LSTM/bert2lstm.py in <module>()
      8 from copy import deepcopy
      9 
---> 10 from transformers import BertForSequenceClassification, AdamW, BertTokenizer
     11 
     12 from KD_Lib.KD.common import BaseClass

ModuleNotFoundError: No module named 'transformers'`

is it any sloution?

**Comment by khizirsiddiqui** [comment] 2021-03-20 13:49
It works fover colab without any issues, see [here](https://colab.research.google.com/drive/1JNSbS6JCZJqqYQMneW6vJ8eeTxwgkc3X?usp=sharing). See if this helps you, or maybe it weirdly didn't install transformers which you can `pip install` anyways.

**Comment by samo313** [comment] 2021-03-20 15:00
> It works over colab without any issues, see [here](https://colab.research.google.com/drive/1JNSbS6JCZJqqYQMneW6vJ8eeTxwgkc3X?usp=sharing). See if this helps you, or maybe it weirdly didn't install transformers which you can `pip install` anyways.

I need some permission to see the link. Could you please confirm it?

**Comment by khizirsiddiqui** [comment] 2021-03-20 16:06
@samo313 can you check again?

**Comment by samo313** [comment] 2021-03-20 17:02
> @samo313 can you check again? I updated the permissions.
I can check your code over colab. thanks

**Comment by khizirsiddiqui** [comment] 2021-03-20 18:30
@samo313 The issue is resolved now, right?

**Comment by samo313** [comment] 2021-03-20 19:44
> @samo313 The issue is resolved now, right?

that's right. I have a new problem in README.rst in the following line:

`distiller.train_students(epochs=5, log=True, logdir="./Logs")`

gives this error:

`TypeError: train_students() got an unexpected keyword argument 'log'`

**Comment by khizirsiddiqui** [comment] 2021-03-20 19:50
Yeah, we haven't really gotten time to push several changes recently. Do you mind sending a PR?

**Comment by Het-Shah** [comment] 2021-03-21 09:47
I have updated the README.rst file, Thank you @samo313  for pointing these out to us. Closing this issue for now. If you still face any issues, feel free to open a new issue. 😄

**Closed by Het-Shah** 2021-03-21 09:47 UTC
